### PR TITLE
Virtual Sprint Commit Data Model Schema

### PR DESCRIPTION
**Pull request by jacebryan**
# Critical Changes

# Changes
- Created new object: Course Equivalency Rules with the following fields:
-- External_Course__c
-- Required_Grade__c
-- End_Date__c
-- Rule_Start_Date
- Created new object: Transcript Course with the following fields:
-- Approval_Status__c
-- Awarded_Credit_Hour__c
-- Course_Equivalent__c
-- Course_to_be_Evaluated__c
-- End_Date__c
-- Start_Date__c
-- Term__c
-- Transcript__c
- Created new object: Transcript with the following fields:
-- Application__c
-- Contact__c
-- Credit_Hours__c
-- Decision_Status__c
-- Education_Institutions__c
-- GPA__c
-- Total_Awarded_Credit_Hours__c</members>
- Added Transcript Evaluation Status picklist field to Application
- Added Course Equivalency Rule lookup to Course
- Introduced 4 new layouts
-- Course Equivalency Rule Layout
-- Course Transfer Layout
-- Transcript Course Layout
-- Transcript Layout
- Granted access to the Course Record Type "Internal" to the System Administrator profile 

# Issues Closed

### CODE REVIEW

**Comment by robertbwatson** [comment]
@jacebryan @IAmEricKenney This looks great! I'm almost ready to approve and merge in, but I do have a couple of questions/comments:

1) Should new Tabs have been created for some of these new objects? (How is an admin supposed to use/set these up?) If so, I can create an Issue for someone to create them in a future sprint.

2) I uncovered a few issues with our existing test data and also other areas where I think we can make improvements. I logged these all as issues that someone might be able to work on in a future sprint:

Related to these new objects:
#40 Update Entity Relationship Diagram & Use Cases
#43 Update Test Data

Bugs:
#42 Fix test data task (test_data_dev_org)

Other/CCI-related:
#41 Update scratch org JSON configuration files

Let me know what you think. Thanks!

**Comment by IAmEricKenney** [comment]
@robertbwatson Yes, a couple of tabs should have been created. How should I get those added?

We created an ERD. Starley might still have it saved.

**Comment by robertbwatson** [comment]
> @robertbwatson Yes, a couple of tabs should have been created. How should I get those added?

Thanks, @IAmEricKenney. I created #44 to get these added; they can be done in a separate pull request or at the next sprint! :)

> We created an ERD. Starley might still have it saved.

Great! I've updated issue #40 with that info.

I don't want to hold up on the merge on this any longer (that way we have it for the next virtual sprint!), so I'll go ahead and merge this now.

**Comment by jacebryan** [comment]
Thank you both!

**Pull request merged**
